name: Deploy EESTEC Webiste

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ID }}
        aws-secret-access-key: ${{ secrets.ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.13.0

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy
      if: success()
      run: | 
        aws s3 sync ./dist/ s3://eestec-website --delete
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

